# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2017

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  Tags: /tags
  # Categories: /categories
  About: /about

# site search option
search: true

# Fancybox
fancybox: true

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default

# ===========================================
# Social links Settings
# ===========================================
social:
  email: libeibei1995@gmail.com
  stack-overflow:
  twitter:
  facebook:
  github: https://github.com/LadyShelley2
  weibo: 
  zhihu: https://www.zhihu.com/people/shelley-lee-94

# ===========================================
# Third Party Services Settings
# ===========================================


# Google Analytics
google_analytics: UA-90357969-1

# Baidu Analytics
baidu_analytics: f29aeed2f059e5c86ef8b128ce0aa248

# Duoshuo
duoshuo_shortname: leebeibei
# Disqus
disqus_shortname: 


# ===========================================
# Version
# ===========================================
version: 2.1.0